title: Zainab Ibrahim
description: 
   An experienced data analyst, proficient in Excel, SQL, PowerBI and Python.
   <a href="https://www.linkedin.com/in/zainab-ibrahim/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
