title: # Zainab  Ibrahim

description: > # your text below (remove <br> elements if you don't need line breaks)
  An experienced data analyst, proficient in Excel, SQL, PowerBI and Python
  <br><br>
  <a href="https://www.linkedin.com/in/zainab-ibrahim/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
